#pragma once
#include <cstring>
static int uiLanguage=0;
static const char* T(const char* zh){
 if(!uiLanguage)return zh;
 if(std::strcmp(zh,u8"等待运行时连接")==0)return "Waiting for the runtime";
 if(std::strcmp(zh,u8"全部品质")==0)return "All rarities";
 if(std::strcmp(zh,u8"普通 / I")==0)return "Common / I";
 if(std::strcmp(zh,u8"稀有 / II")==0)return "Rare / II";
 if(std::strcmp(zh,u8"史诗 / III")==0)return "Epic / III";
 if(std::strcmp(zh,u8"星界")==0)return "Astral";
 if(std::strcmp(zh,u8"全部元素")==0)return "All elements";
 if(std::strcmp(zh,u8"火")==0)return "Fire";
 if(std::strcmp(zh,u8"冰")==0)return "Ice";
 if(std::strcmp(zh,u8"雷")==0)return "Lightning";
 if(std::strcmp(zh,u8"毒")==0)return "Poison";
 if(std::strcmp(zh,u8"通用")==0)return "Neutral";
 if(std::strcmp(zh,u8"星界战士 · BD 选择")==0)return "Astral Ascent \u00b7 Build Selector";
 if(std::strcmp(zh,u8"LB/RB 切页 · 上下/左摇杆选择 · LT/RT 快速翻页 · B 收起")==0)return "LB/RB: tabs \u00b7 Up/Down: select \u00b7 LT/RT: jump \u00b7 B: close";
 if(std::strcmp(zh,u8"F8 或 Back＋Start 打开或关闭。进入本轮后可立即装配。版本：2.6.4")==0)return "F8 or Back+Start: open/close. Apply immediately during a run. Game: 2.6.4";
 if(std::strcmp(zh,u8"BD 构筑")==0)return "Builds";
 if(std::strcmp(zh,u8"左右切换模式 · A 立即装配 · X 领取成长补给")==0)return "Left/Right: mode \u00b7 A: equip \u00b7 X: claim growth reward";
 if(std::strcmp(zh,u8"成型模式")==0)return "Complete";
 if(std::strcmp(zh,u8"成长模式")==0)return "Growth";
 if(std::strcmp(zh,u8"立即替换五个光环、四个法术及首槽符文，并保存本轮装备。")==0)return "Replace 5 auras, 4 spells and gambits; save the current loadout.";
 if(std::strcmp(zh,u8"立即装配法术，随后四次补给逐步发放五个光环与符文。")==0)return "Equip spells now; collect auras and gambits in 4 growth rewards.";
 if(std::strcmp(zh,u8"领取成长补给")==0)return "Claim growth reward";
 if(std::strcmp(zh,u8"立即装配此 BD")==0)return "Equip this build";
 if(std::strcmp(zh,u8"光环自选")==0)return "Custom Auras";
 if(std::strcmp(zh,u8"仅修改所选光环槽，立即生效并保存；支持重复光环。")==0)return "Replace only the selected aura slot and save immediately. Duplicates supported.";
 if(std::strcmp(zh,u8"方案名（可选）")==0)return "Name (optional)";
 if(std::strcmp(zh,u8"保存当前五槽")==0)return "Save 5 slots";
 if(std::strcmp(zh,u8"已保存方案")==0)return "Saved plans";
 if(std::strcmp(zh,u8"等级 / 品质")==0)return "Rarity";
 if(std::strcmp(zh,u8"元素")==0)return "Element";
 if(std::strcmp(zh,u8"搜索名称（可选）")==0)return "Search (optional)";
 if(std::strcmp(zh,u8"重置筛选")==0)return "Reset filters";
 if(std::strcmp(zh,u8"右摇杆：等级 · X：元素 · 左右：槽位 · A：装备 · Y：清空槽 · 左摇杆按下：重置筛选")==0)return "R-stick click: rarity \u00b7 X: element \u00b7 Left/Right: slot \u00b7 A: equip \u00b7 Y: clear \u00b7 L-stick click: reset";
 if(std::strcmp(zh,u8"当前分类：%d 项")==0)return "Matching auras: %d";
 if(std::strcmp(zh,u8"没有匹配光环，请切换分类或重置筛选。")==0)return "No matching auras. Change or reset filters.";
 if(std::strcmp(zh,u8"光环槽 1")==0)return "Aura slot 1";
 if(std::strcmp(zh,u8"光环槽 2")==0)return "Aura slot 2";
 if(std::strcmp(zh,u8"光环槽 3")==0)return "Aura slot 3";
 if(std::strcmp(zh,u8"光环槽 4")==0)return "Aura slot 4";
 if(std::strcmp(zh,u8"光环槽 5")==0)return "Aura slot 5";
 if(std::strcmp(zh,u8"目标槽位")==0)return "Target slot";
 if(std::strcmp(zh,u8"立即装备 / 替换")==0)return "Equip / replace";
 if(std::strcmp(zh,u8"清空此槽")==0)return "Clear slot";
 if(std::strcmp(zh,u8"光环方案")==0)return "Aura Plans";
 if(std::strcmp(zh,u8"保存当前五个光环槽；应用时一次替换五槽，包含空槽。法术保持当前配置。")==0)return "Save all 5 aura slots, including empty slots. Applying a plan keeps spells and gambits.";
 if(std::strcmp(zh,u8"方案名（留空自动命名）")==0)return "Name (blank = automatic)";
 if(std::strcmp(zh,u8"保存当前五槽为新方案")==0)return "Save current 5 slots";
 if(std::strcmp(zh,u8"上下选择方案 · LT/RT 快速翻页 · A 立即应用 · X 保存当前五槽")==0)return "Up/Down: select \u00b7 LT/RT: jump \u00b7 A: apply \u00b7 X: save current slots";
 if(std::strcmp(zh,u8"已保存：%d 个方案")==0)return "Saved plans: %d";
 if(std::strcmp(zh,u8"还没有保存方案。先配置光环，再点击保存当前五槽。")==0)return "No plans yet. Equip auras, then save the current slots.";
 if(std::strcmp(zh,u8"立即应用此光环方案")==0)return "Apply selected plan";
 if(std::strcmp(zh,u8"关闭 Mod")==0)return "Disable Mod";
 if(std::strcmp(zh,u8"收起界面")==0)return "Close menu";
 return zh;
}
